# Generated by Django 6.0.6 on 2026-06-21 02:35

import home.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('services_grid', 9), ('testimonials', 11), ('staff_list', 13), ('faq', 15), ('feature_section', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('link_url', 4), ('link_page', 5)]], {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('primary_button', 6), ('secondary_button', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (home.blocks.ServiceItemBlock,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('services', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (home.blocks.TestimonialItemBlock,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('testimonials', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (home.blocks.StaffMemberBlock,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('members', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (home.blocks.FaqItemBlock,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('items', 14)]], {}), 16: ('wagtail.blocks.RichTextBlock', (), {}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image on Left'), ('right', 'Image on Right')]}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 16), ('image', 17), ('image_alignment', 18), ('button', 6)]], {})}, null=True),
        ),
    ]
